### ISSUE TITLE
Start at specific value

### ISSUE THREAD

**Issue by alexjordaan** [agilie/AGCircularPicker#6]
Hi.
I have the picker working great with decimals by just diving the end value by 10 as you suggested. When I return to the picker I would like to set the control to the last used value. I initialize it starting at zero and going to 100 for example but would like it to be selected at an interim value, say 40 ie: remembers the last value since each time the picker is used it is to adjust the previous recorded value.

Is this possible?

**Comment by savilov** [comment]
Hi @alexjordaan, sorry for the delay. We've released 0.1.6 version with possibility to define initial value in `AGCircularPickerValueOption`. Please see the update example for details. Let me know if you still have any issues with it

**Comment by alexjordaan** [comment]
Thank you, thats great of you! I updated to 0.1.6 and I see the option. Initial tests don't seem to work but I'll work on it a bit to see if it's something simple. Setting the initialValue should visually start the picker at that value right? On mine it still starts at 12 o'clock despite me setting an initialValue of 25 with a maxValue of 100. I would expect the marker to start at 3 o'clock right?

**Comment by savilov** [comment]
@alexjordaan, yeah, there's an issue because of supporting reuse for collection view. We will think on how to fix it correctly. For now you can use something like this:

`        let valueOption = AGCircularPickerValueOption(minValue: 0, maxValue: 100)`
`        let titleOption = AGCircularPickerTitleOption(title: "volume")`
`        let option = AGCircularPickerOption(valueOption: valueOption, titleOption: titleOption)`
`        pickerView.setupPicker(delegate: self, option: option, value: 25)`

**Comment by alexjordaan** [comment]
That's perfect. Thank you so much! Love your work.

**Comment by savilov** [comment]
Hi @alexjordaan, since 0.1.7 you can use initial value as listed in sample:

`        let valueOption = AGCircularPickerValueOption(minValue: 0, maxValue: 100, initialValue: 50)`
`        let titleOption = AGCircularPickerTitleOption(title: "volume")`
`        let option = AGCircularPickerOption(valueOption: valueOption, titleOption: titleOption)`
`        pickerView.setupPicker(delegate: self, option: option)`
